### ISSUE TITLE
Problem with openXR when I built the project

### ISSUE THREAD

**Issue by Clashman16** [ReliaSolve/OpenXR-OpenGL-Example#2]
Hi,
I don't succed to build the project because CMake doesnot find OpenXR in my files.
However, I downloaded the sources of the SDK from the official Khronos OPenXR repository.
I have the following error :
```
1> [CMake]   Could not find a package configuration file provided by "OpenXR" with any
1> [CMake]   of the following names:
1> [CMake] 
1> [CMake]     OpenXRConfig.cmake
1> [CMake]     openxr-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "OpenXR" to CMAKE_PREFIX_PATH or set
1> [CMake]   "OpenXR_DIR" to a directory containing one of the above files.  If "OpenXR"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.
```
Can u help me, please ?
What can I do to resolve the problem ?

Thanks for answers !

**Comment by russell-taylor** [comment]
You need to install the SDK before it can be located by CMake.  For me, on Windows it is found and uses the configuration file "C:/Program Files (x86)/OPENXR/cmake".

I've added a FindOpenXR.cmake file to try and make this more general.  Once you have installed the SDK, go ahead and pull the changes and see if it can find OpenXR now.

**Comment by Clashman16** [comment]
> 

Thanks for your help !
However, your FindOpenXR.cmake file does not find my SDK.
Do you think it will work if I move my SDK in Proram Files folder ?

**Comment by Clashman16** [comment]
I didn't see that I have to replace strings by my paths.
But it 's still not working after I changed that.

`# Set up cache variables
set(OPENXR_SDK_SRC_DIR
    "${OPENXR_SDK_SRC_DIR}"
    CACHE
        PATH
        "C:/Users/Lilian/Documents/Nouveau dossier/OpenXR-SDK-Source"
)
set(OPENXR_SDK_BUILD_DIR
    "${OPENXR_SDK_BUILD_DIR}"
    CACHE
        PATH
        "C:/Users/Lilian/Documents/Nouveau dossier/OpenXR-SDK-Source/build/win64"
)`

Can you tell me what is wrong please ?

**Comment by russell-taylor** [comment]
You will need to compile and install the SDK/loader, not just download it.  What operating system are you using?

**Comment by Clashman16** [comment]
I compled the sdk before donloading your sample. I am using Windows 10.

**Comment by russell-taylor** [comment]
You'll need to install the sample (which I think requires running Visual Studio as root and building the "INSTALL" target.  Once that has been done, it should create the "C:/Program Files (x86)/OPENXR" folder.  I think it should find that target automatically once the folder is in place.  If it does not find the target with that folder in place, we'll need to tweak the FindOpenXR.cmake file.

**Comment by russell-taylor** [comment]
I'm assuming that this solved your problem. Please re-open the issue if not.
